name: flutter_pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  graphql_flutter: ^5.1.2
  connectivity_plus: ^6.1.0
  convex_bottom_bar: ^3.0.0
  flutter_speed_dial: ^6.1.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: PokemonSolid
      fonts:
        - asset: assets/fonts/PokemonSolid.ttf
    - family: PokemonHollow
      fonts:
        - asset: assets/fonts/PokemonHollow.ttf
